name: Build & Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  # 使用 Node.js 20 版本

      - name: Install dependencies
        run: npm install --prefix frontend  # 使用 npm install 生成 package-lock.json 文件

      - name: Install gh-pages
        run: npm install gh-pages --save-dev --prefix frontend  # 安装 gh-pages

      - name: Build the project
        run: npm run build --prefix frontend

      - name: Deploy to GitHub Pages
        run: npm run deploy --prefix frontend  # 使用 gh-pages 部署
