name: Build & Deploy Frontend
on:
  push:
    branches: [ main ]

# 关键：给 GITHUB_TOKEN 写权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: frontend
        run: npm install

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Configure git user
        run: |
          git config --global user.email "Eysn0130@users.noreply.github.com"
          git config --global user.name "Eysn0130"

      # 用 Actions 提供的 GITHUB_TOKEN 进行推送
      - name: Deploy to gh-pages
        working-directory: frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 让 gh-pages CLI 使用 token（支持 GITHUB_TOKEN/GH_TOKEN 环境变量）
          npx gh-pages -d dist -u "github-actions[bot] <actions@github.com>"
          # 如果你坚持用 npm script: npm run deploy 也行，只要保留上面的 env
